name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  SERVICE:
    description: "Service to build"
    required: true
  IMAGE_NAME:
    description: "Name of image"
    required: true
  REGISTRY_USERNAME:
    description: "Registry username"
    required: true
  REGISTRY_PASSWORD:
    description: "Registry password"
    required: true

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

runs:
  using: "composite"

  steps:
    # - name: Enable experimental features for the Docker daemon and CLI
    #   shell: bash
    #   run: |
    #     echo $'{\n  "experimental": true\n}' | sudo tee /etc/docker/daemon.json
    #     mkdir -p ~/.docker
    #     echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
    #     sudo service docker restart

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
