name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  SERVICE:
    description: "Service to build"
    required: true
  IMAGE_NAME:
    description: "Name of image"
    required: true
  REGISTRY:
    description: "Registry"
    required: true
  REGISTRY_USERNAME:
    description: "Registry username"
    required: true
  REGISTRY_PASSWORD:
    description: "Registry password"
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.REGISTRY_USERNAME }}
        password: ${{ inputs.REGISTRY_PASSWORD }}

    - name: Set branch name as env variable
      run: |
        currentbranch=$(echo ${GITHUB_REF##*/})
        echo "running on $currentbranch"
        echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      shell: bash

    - name: Compose build ${{ inputs.service }}
      shell: bash
      run: sudo -E docker-compose build ${{ inputs.service }} --no-start
      working-directory: ./src
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ inputs.REGISTRY }}

    - name: Compose push ${{ inputs.service }}
      shell: bash
      run: sudo -E docker-compose push ${{ inputs.service }}
      working-directory: ./src
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ inputs.REGISTRY }}
