FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

EXPOSE 4000 4200 4433 5000 8080 9876

RUN npm i -g @angular/cli@latest

# Go! (And keep going.)
#CMD ["tail", "--follow", "/dev/null"]
