FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

EXPOSE 4000 4200 4433 5000 8080 9876

# Switch to `root` (CircleCI images use `circleci` as the user).
#USER root

# Configure `Node.js`/`npm`.
#RUN npm config --global set user root

# Go! (And keep going.)
#CMD ["tail", "--follow", "/dev/null"]
