name: "Web CI/CD"

on:
  push:
    branches:
      - dev
    paths:
      - src/web/**
      - .github/workflows/webspa.yml
      
  pull_request:
    branches:
      - dev
    paths:
      - src/web/**
      - .github/workflows/webspa.yml

env:
  SERVICE: webspa
  IMAGE: webspa

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-push
        with:
          service: ${{ env.SERVICE }}
          image_name: ${{ env.IMAGE }}
