name: "Web build & publish"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - src/web/**
      - .github/workflows/webspa.yml

  pull_request:
    branches:
      - dev
    paths:
      - src/web/**
      - .github/workflows/webspa.yml

env:
  SERVICE: webspa
  IMAGE: webspa

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/build-push
        with:
          SERVICE: ${{ env.SERVICE }}
          IMAGE_NAME: ${{ env.IMAGE }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
