name: "Web build & publish"

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - src/web/**
      - .github/workflows/webspa.yml

  pull_request:
    branches:
      - dev
    paths:
      - src/web/**
      - .github/workflows/webspa.yml

env:
  REGISTRY: ghcr.io
  SERVICE: webspa
  IMAGE: webspa

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: ./.github/workflows/composite/build-push
        with:
          SERVICE: ${{ env.SERVICE }}
          IMAGE_NAME: ${{ env.IMAGE }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
